# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

inhibit_all_warnings!

target "MRGLocaleDemo" do
  pod 'MRGControlPanel', '~> 0.0.4'
end

target "MRGLocaleTests" do

end

