source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:mirego/MCPodSpecs.git'

platform :ios, '6.0'

pod 'MRGLocale', :path => '../MRGLocale.podspec'

# Unit Tests Pods
target :MRGLocaleDemoTests do
end
